package com.jeff.model;
// Generated 2016-11-20 16:51:05 by Hibernate Tools 4.0.1.Final

/**
 * Bridge generated by hbm2java
 */
public class Bridge implements java.io.Serializable {

	private Integer id;
	private String univCode;
	private String majorCode;
	private String year;

	public Bridge() {
	}

	public Bridge(String univCode, String majorCode, String year) {
		this.univCode = univCode;
		this.majorCode = majorCode;
		this.year = year;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	public String getMajorCode() {
		return this.majorCode;
	}

	public void setMajorCode(String majorCode) {
		this.majorCode = majorCode;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
