package com.jeff.model;
// Generated 2016-11-20 16:51:05 by Hibernate Tools 4.0.1.Final

/**
 * Major generated by hbm2java
 */
public class Major implements java.io.Serializable {

	private String majorCode;
	private String majorName;
	private String specCode;
	private String majorDegree;
	private String majorLength;
	private String mainDiscipline;
	private String mainCourse;
	private String majorGoal;
	private String majorRequire;
	private String stuAbility;
	private String majorPractice;
	private String bookRecommender;
	private String majorTest;
	private String majorEval;
	private String majorPayment;
	private String majorEmploy;
	private String majorToward;
	private String masterInfo;
	private String abroadInfo;
	private String majorIntro;

	public Major() {
	}

	public Major(String majorCode) {
		this.majorCode = majorCode;
	}

	public Major(String majorCode, String majorName, String specCode, String majorDegree, String majorLength,
			String mainDiscipline, String mainCourse, String majorGoal, String majorRequire, String stuAbility,
			String majorPractice, String bookRecommender, String majorTest, String majorEval, String majorPayment,
			String majorEmploy, String majorToward, String masterInfo, String abroadInfo, String majorIntro) {
		this.majorCode = majorCode;
		this.majorName = majorName;
		this.specCode = specCode;
		this.majorDegree = majorDegree;
		this.majorLength = majorLength;
		this.mainDiscipline = mainDiscipline;
		this.mainCourse = mainCourse;
		this.majorGoal = majorGoal;
		this.majorRequire = majorRequire;
		this.stuAbility = stuAbility;
		this.majorPractice = majorPractice;
		this.bookRecommender = bookRecommender;
		this.majorTest = majorTest;
		this.majorEval = majorEval;
		this.majorPayment = majorPayment;
		this.majorEmploy = majorEmploy;
		this.majorToward = majorToward;
		this.masterInfo = masterInfo;
		this.abroadInfo = abroadInfo;
		this.majorIntro = majorIntro;
	}

	public String getMajorCode() {
		return this.majorCode;
	}

	public void setMajorCode(String majorCode) {
		this.majorCode = majorCode;
	}

	public String getMajorName() {
		return this.majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public String getSpecCode() {
		return this.specCode;
	}

	public void setSpecCode(String specCode) {
		this.specCode = specCode;
	}

	public String getMajorDegree() {
		return this.majorDegree;
	}

	public void setMajorDegree(String majorDegree) {
		this.majorDegree = majorDegree;
	}

	public String getMajorLength() {
		return this.majorLength;
	}

	public void setMajorLength(String majorLength) {
		this.majorLength = majorLength;
	}

	public String getMainDiscipline() {
		return this.mainDiscipline;
	}

	public void setMainDiscipline(String mainDiscipline) {
		this.mainDiscipline = mainDiscipline;
	}

	public String getMainCourse() {
		return this.mainCourse;
	}

	public void setMainCourse(String mainCourse) {
		this.mainCourse = mainCourse;
	}

	public String getMajorGoal() {
		return this.majorGoal;
	}

	public void setMajorGoal(String majorGoal) {
		this.majorGoal = majorGoal;
	}

	public String getMajorRequire() {
		return this.majorRequire;
	}

	public void setMajorRequire(String majorRequire) {
		this.majorRequire = majorRequire;
	}

	public String getStuAbility() {
		return this.stuAbility;
	}

	public void setStuAbility(String stuAbility) {
		this.stuAbility = stuAbility;
	}

	public String getMajorPractice() {
		return this.majorPractice;
	}

	public void setMajorPractice(String majorPractice) {
		this.majorPractice = majorPractice;
	}

	public String getBookRecommender() {
		return this.bookRecommender;
	}

	public void setBookRecommender(String bookRecommender) {
		this.bookRecommender = bookRecommender;
	}

	public String getMajorTest() {
		return this.majorTest;
	}

	public void setMajorTest(String majorTest) {
		this.majorTest = majorTest;
	}

	public String getMajorEval() {
		return this.majorEval;
	}

	public void setMajorEval(String majorEval) {
		this.majorEval = majorEval;
	}

	public String getMajorPayment() {
		return this.majorPayment;
	}

	public void setMajorPayment(String majorPayment) {
		this.majorPayment = majorPayment;
	}

	public String getMajorEmploy() {
		return this.majorEmploy;
	}

	public void setMajorEmploy(String majorEmploy) {
		this.majorEmploy = majorEmploy;
	}

	public String getMajorToward() {
		return this.majorToward;
	}

	public void setMajorToward(String majorToward) {
		this.majorToward = majorToward;
	}

	public String getMasterInfo() {
		return this.masterInfo;
	}

	public void setMasterInfo(String masterInfo) {
		this.masterInfo = masterInfo;
	}

	public String getAbroadInfo() {
		return this.abroadInfo;
	}

	public void setAbroadInfo(String abroadInfo) {
		this.abroadInfo = abroadInfo;
	}

	public String getMajorIntro() {
		return this.majorIntro;
	}

	public void setMajorIntro(String majorIntro) {
		this.majorIntro = majorIntro;
	}

}
