package com.jeff.model;
// Generated 2016-11-20 16:51:05 by Hibernate Tools 4.0.1.Final

/**
 * Univ generated by hbm2java
 */
public class Univ implements java.io.Serializable {

	private String univCode;
	private String univName;
	private String univCtime;
	private String univ211;
	private String univ985;
	private String univProvince;
	private String univSubjection;
	private String univType;
	private String univHost;
	private String univLevel;
	private String univPhone;
	private String univWebsite;
	private String univAddress;
	private String univNas;
	private String univPhds;
	private String univMasters;
	private String univIntro;
	private String univKeyDiscipline;
	private String univFaculty;
	private String univAward;
	private String univStudent;
	private String univSchoolmate;
	private String univSpecialty;

	public Univ() {
	}

	public Univ(String univCode, String univName) {
		this.univCode = univCode;
		this.univName = univName;
	}

	public Univ(String univCode, String univName, String univCtime, String univ211, String univ985, String univProvince,
			String univSubjection, String univType, String univHost, String univLevel, String univPhone,
			String univWebsite, String univAddress, String univNas, String univPhds, String univMasters,
			String univIntro, String univKeyDiscipline, String univFaculty, String univAward, String univStudent,
			String univSchoolmate, String univSpecialty) {
		this.univCode = univCode;
		this.univName = univName;
		this.univCtime = univCtime;
		this.univ211 = univ211;
		this.univ985 = univ985;
		this.univProvince = univProvince;
		this.univSubjection = univSubjection;
		this.univType = univType;
		this.univHost = univHost;
		this.univLevel = univLevel;
		this.univPhone = univPhone;
		this.univWebsite = univWebsite;
		this.univAddress = univAddress;
		this.univNas = univNas;
		this.univPhds = univPhds;
		this.univMasters = univMasters;
		this.univIntro = univIntro;
		this.univKeyDiscipline = univKeyDiscipline;
		this.univFaculty = univFaculty;
		this.univAward = univAward;
		this.univStudent = univStudent;
		this.univSchoolmate = univSchoolmate;
		this.univSpecialty = univSpecialty;
	}

	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	public String getUnivName() {
		return this.univName;
	}

	public void setUnivName(String univName) {
		this.univName = univName;
	}

	public String getUnivCtime() {
		return this.univCtime;
	}

	public void setUnivCtime(String univCtime) {
		this.univCtime = univCtime;
	}

	public String getUniv211() {
		return this.univ211;
	}

	public void setUniv211(String univ211) {
		this.univ211 = univ211;
	}

	public String getUniv985() {
		return this.univ985;
	}

	public void setUniv985(String univ985) {
		this.univ985 = univ985;
	}

	public String getUnivProvince() {
		return this.univProvince;
	}

	public void setUnivProvince(String univProvince) {
		this.univProvince = univProvince;
	}

	public String getUnivSubjection() {
		return this.univSubjection;
	}

	public void setUnivSubjection(String univSubjection) {
		this.univSubjection = univSubjection;
	}

	public String getUnivType() {
		return this.univType;
	}

	public void setUnivType(String univType) {
		this.univType = univType;
	}

	public String getUnivHost() {
		return this.univHost;
	}

	public void setUnivHost(String univHost) {
		this.univHost = univHost;
	}

	public String getUnivLevel() {
		return this.univLevel;
	}

	public void setUnivLevel(String univLevel) {
		this.univLevel = univLevel;
	}

	public String getUnivPhone() {
		return this.univPhone;
	}

	public void setUnivPhone(String univPhone) {
		this.univPhone = univPhone;
	}

	public String getUnivWebsite() {
		return this.univWebsite;
	}

	public void setUnivWebsite(String univWebsite) {
		this.univWebsite = univWebsite;
	}

	public String getUnivAddress() {
		return this.univAddress;
	}

	public void setUnivAddress(String univAddress) {
		this.univAddress = univAddress;
	}

	public String getUnivNas() {
		return this.univNas;
	}

	public void setUnivNas(String univNas) {
		this.univNas = univNas;
	}

	public String getUnivPhds() {
		return this.univPhds;
	}

	public void setUnivPhds(String univPhds) {
		this.univPhds = univPhds;
	}

	public String getUnivMasters() {
		return this.univMasters;
	}

	public void setUnivMasters(String univMasters) {
		this.univMasters = univMasters;
	}

	public String getUnivIntro() {
		return this.univIntro;
	}

	public void setUnivIntro(String univIntro) {
		this.univIntro = univIntro;
	}

	public String getUnivKeyDiscipline() {
		return this.univKeyDiscipline;
	}

	public void setUnivKeyDiscipline(String univKeyDiscipline) {
		this.univKeyDiscipline = univKeyDiscipline;
	}

	public String getUnivFaculty() {
		return this.univFaculty;
	}

	public void setUnivFaculty(String univFaculty) {
		this.univFaculty = univFaculty;
	}

	public String getUnivAward() {
		return this.univAward;
	}

	public void setUnivAward(String univAward) {
		this.univAward = univAward;
	}

	public String getUnivStudent() {
		return this.univStudent;
	}

	public void setUnivStudent(String univStudent) {
		this.univStudent = univStudent;
	}

	public String getUnivSchoolmate() {
		return this.univSchoolmate;
	}

	public void setUnivSchoolmate(String univSchoolmate) {
		this.univSchoolmate = univSchoolmate;
	}

	public String getUnivSpecialty() {
		return this.univSpecialty;
	}

	public void setUnivSpecialty(String univSpecialty) {
		this.univSpecialty = univSpecialty;
	}

}
